"""
Wordlists for Diceware passphrases and common leaked passwords blacklist.
"""

# Top frequently breached and common weak passwords for instant offline detection
COMMON_PASSWORDS = {
    "123456", "password", "12345678", "qwerty", "123456789", "12345", "1234",
    "111111", "1234567", "dragon", "123123", "baseball", "football", "monkey",
    "letmein", "sunshine", "iloveyou", "trustno1", "princess", "admin", "welcome",
    "shadow", "master", "superman", "starwars", "password123", "killer", "login",
    "pass1234", "charlie", "freedom", "whatever", "secret", "computer", "testing",
    "qwertyuiop", "asdfghjkl", "zxcvbnm", "default", "root", "toor", "access",
    "hunter2", "myspace1", "fluffy", "orange", "yellow", "purple", "guest",
    "internet", "soccer", "pepper", "harley", "angel", "test", "master123",
    "123321", "654321", "666666", "777777", "888888", "999999", "000000",
    "qazwsx", "wsxedc", "edcrfv", "pass@123", "password@123", "admin123",
    "p@ssword", "p@ssw0rd", "passw0rd", "adobe123", "system", "administrator"
}

# Curated high-quality Diceware wordlist for memorable, high-entropy passphrases
# Sourced from standard EFF short/general wordlists: unambiguous, easy to spell, 3-7 characters
DICEWARE_WORDS = [
    "acid", "acorn", "actor", "adore", "agent", "agile", "ahead", "aim", "alarm",
    "album", "alert", "alien", "alive", "alley", "alpha", "amber", "amaze", "angel",
    "angle", "apple", "apron", "aqua", "arcade", "arena", "armor", "arrow", "artist",
    "atlas", "atomic", "audio", "aura", "autumn", "avatar", "badge", "baker", "bamboo",
    "banner", "baron", "barrel", "beacon", "beast", "beauty", "beetle", "binary", "bird",
    "bishop", "blade", "blazer", "blend", "bliss", "blizzard", "bloom", "bluff", "blur",
    "board", "bold", "bonus", "border", "botany", "bounce", "brave", "breeze", "brick",
    "bridge", "bronze", "bubble", "bullet", "bundle", "cabin", "cactus", "cadet", "calm",
    "camera", "camp", "candle", "canyon", "canvas", "captain", "carbon", "card", "carpet",
    "castle", "cave", "cedar", "celery", "census", "chalk", "champion", "chant", "chaos",
    "charm", "cherry", "chess", "chief", "circle", "city", "clam", "clarity", "cliff",
    "climb", "cloak", "clover", "coach", "coast", "cobra", "coffee", "coin", "colony",
    "comet", "compass", "copper", "coral", "corner", "cosmos", "cotton", "crane", "crater",
    "credit", "creek", "crisp", "crown", "crystal", "cube", "curtain", "cypher", "dagger",
    "daisy", "dancer", "daring", "dawn", "daylight", "delta", "desert", "device", "diamond",
    "dime", "dinner", "direct", "diver", "dizzy", "doctor", "dolphin", "domain", "donkey",
    "double", "dragon", "drift", "drive", "drone", "drum", "dune", "eagle", "earth",
    "echo", "eclipse", "edge", "editor", "elbow", "elder", "element", "elite", "ember",
    "emerald", "empire", "energy", "engine", "enigma", "epic", "epoch", "equal", "escape",
    "estate", "ethics", "everest", "exhibit", "expand", "exotic", "expert", "falcon", "fame",
    "fancy", "farmer", "feather", "feline", "fence", "fern", "fever", "field", "filter",
    "finch", "finger", "firefly", "flame", "flask", "fleet", "flint", "floral", "flower",
    "flying", "focus", "forest", "forge", "fossil", "fox", "fragile", "freeze", "frost",
    "galaxy", "garden", "garlic", "gas", "gate", "gecko", "genius", "gentle", "ginger",
    "glacier", "glance", "glider", "globe", "glory", "glow", "goblin", "gold", "gorilla",
    "grain", "granite", "grape", "grass", "gravity", "guitar", "guru", "hammer", "harbor",
    "harvest", "haven", "hawk", "hazel", "header", "heart", "helmet", "hero", "hidden",
    "hill", "hint", "honey", "horizon", "horse", "hotel", "humble", "hunter", "hybrid",
    "iceberg", "icon", "impact", "indigo", "infant", "inland", "insect", "island", "ivory",
    "jacket", "jaguar", "jasper", "javelin", "jazz", "jelly", "jewel", "jockey", "joker",
    "journey", "judge", "juice", "jungle", "junior", "jupiter", "karma", "kayak", "keeper",
    "kernel", "kettle", "key", "kinetic", "king", "kite", "kitten", "kiwi", "knight",
    "koala", "ladder", "lake", "lamp", "lantern", "laser", "lava", "layout", "leader",
    "leaf", "legend", "lemon", "leopard", "liberty", "light", "lightning", "lily", "linear",
    "lion", "liquid", "lizard", "llama", "lobster", "logic", "lotus", "lumber", "lunar",
    "luxury", "lynx", "magic", "magnet", "magnolia", "major", "mango", "mantis", "maple",
    "marble", "marine", "matrix", "meadow", "melody", "melon", "mentor", "mercury", "metal",
    "meteor", "micro", "mimic", "miner", "mint", "mirror", "mission", "mist", "mixer",
    "mobile", "modem", "monkey", "moon", "mosaic", "moss", "motion", "motor", "mountain",
    "music", "mystery", "nebula", "nectar", "needle", "neon", "nest", "neutron", "nexus",
    "ninja", "noble", "nomad", "nova", "novel", "oasis", "object", "ocean", "octave",
    "olive", "olympic", "omega", "online", "onyx", "opal", "open", "opera", "orbit",
    "orchard", "orchid", "origin", "ostrich", "otter", "oxygen", "oyster", "ozone", "paddle",
    "palace", "palette", "panda", "panther", "papaya", "paper", "paradise", "parrot", "partner",
    "passport", "patrol", "peak", "pearl", "pebble", "pelican", "penguin", "pepper", "phantom",
    "phoenix", "piano", "pilot", "pine", "pioneer", "pirate", "pistol", "pixel", "planet",
    "plasma", "plover", "plume", "pocket", "poetry", "polar", "poppy", "portal", "potion",
    "power", "prism", "project", "prophet", "pulse", "puma", "pumpkin", "puzzle", "pyramid",
    "quantum", "quarry", "quartz", "quasar", "queen", "quest", "quick", "quiver", "rabbit",
    "radar", "radius", "rainbow", "raptor", "raven", "rebel", "record", "redwood", "reef",
    "relic", "rescue", "rhino", "rhythm", "ribbon", "rider", "ridge", "rifle", "ripple",
    "river", "robot", "rocket", "rooster", "rover", "ruby", "runner", "safari", "sailor",
    "salmon", "sand", "sapphire", "saturn", "scale", "scarlet", "scenic", "scholar", "scout",
    "scroll", "seal", "secret", "sensor", "serpent", "shadow", "shimmer", "ship", "signal",
    "silent", "silver", "siren", "skate", "skull", "skyline", "slate", "sloth", "smart",
    "smile", "smoke", "snail", "sniper", "solar", "soldier", "spark", "sparrow", "spear",
    "spectrum", "sphinx", "spider", "spiral", "spirit", "splash", "spring", "sprint", "sprite",
    "squid", "stable", "stadium", "stalker", "star", "statue", "stealth", "stone", "storm",
    "summit", "sunflower", "sunset", "surge", "swift", "sword", "symbol", "tactics", "tailor",
    "talon", "tango", "tarot", "temple", "tempo", "tennis", "terra", "thunder", "tiger",
    "timber", "titan", "toast", "topaz", "tornado", "torpedo", "tourist", "tower", "tracer",
    "track", "trail", "train", "trench", "triad", "tribal", "trophy", "tropic", "trumpet",
    "tulip", "tundra", "tunnel", "turtle", "twilight", "typhoon", "ultra", "umbrella", "unicorn",
    "unity", "uranium", "urban", "valiant", "valley", "valve", "vapor", "vault", "vector",
    "velvet", "venture", "venus", "vessel", "vibrant", "victor", "viking", "village", "vintage",
    "violet", "viper", "virtual", "vision", "visitor", "visual", "vortex", "voyage", "vulture",
    "walrus", "warrior", "wave", "weapon", "whisper", "willow", "wind", "winter", "wizard",
    "wolf", "wombat", "wonder", "wrench", "xray", "yacht", "yard", "yellow", "zenith",
    "zephyr", "zero", "zigzag", "zipper", "zodiac", "zone"
]
